name: Manual Deployment Docker Image
on:
  create:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch'
        required: true
        default: 'master'
      imagetag:
        description: 'image tag'
        required: true
        default: 'latest'
      registry:
        description: 'registry (github/docker)'
        required: true
        default: 'github'
      target:
        description: 'Dockerfile target'
        required: true
        default: 'release'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log
        run: |
          echo "date:          $(date +'%d-%m-%Y %H:%M:%S')"
          echo "actor:         ${{ github.actor }}"
          echo "git repo:      ${{ github.repository }}"
          echo "git ref:       ${{ github.event.inputs.branch }}"
          echo "imagetag:      ${{ github.event.inputs.imagetag }}"
          echo "registry:      ${{ github.event.inputs.registry }}"
          echo "docker target: ${{ github.event.inputs.target }}"

      - name: Input validation
        if: github.event.inputs.imagetag != 'latest' ||
            (github.event.inputs.registry != 'github' &&
            github.event.inputs.registry != 'docker') ||
            github.event.inputs.target != 'release' || 
            github.actor != 'edgelessci'
        run: exit 1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          path: deploy

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push ${{ github.repository }}:${{ github.event.inputs.imageTag }} with target ${{ github.event.inputs.target }} to ${{ github.event.inputs.registry }} registry
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
          echo ${{ secrets.CI_GITHUB_DEPLOY }} | docker login ghcr.io --username edgelessci --password-stdin
          echo "machine github.com login ${{ secrets.CI_GITHUB_REPOS }} password ${{ secrets.CI_GITHUB_REPOS }}" > .netrc
          docker buildx build --secret id=repoaccess,src=.netrc \
                              --target ${{ github.event.inputs.target }} \
                              --tag ghcr.io/$REPOSITORY:${{ github.event.inputs.imagetag }} \
                              --push .
          docker logout ghcr.io
          rm .netrc
          rm -f ${{ github.workspace }}/.docker/config.json
        working-directory: deploy

      - name: Image digest
        run: echo ${{ steps.dockerhub_build.outputs.digest }}
 