name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/edgelesssys/edgelessrt-private:latest
      credentials:
        username: ${{ secrets.CI_GITHUB_PACKAGES_READ }}
        password: ${{ secrets.CI_GITHUB_PACKAGES_READ }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: coordinator

    - name: Test core
      run: ertgo test 
      working-directory: coordinator/coordinator/core

    - name: Test server
      run: ertgo test 
      working-directory: coordinator/coordinator/server

    - name: Test marble
      run: ertgo test 
      working-directory: coordinator/marble/marble
