apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: marble-injector-cfg
  labels:
    app: marble-injector
webhooks:
  - name: marble-injector.marblerun.svc.cluster.local
    clientConfig:
      caBundle: ${CA_BUNDLE}
      service:
        name: marble-injector-svc
        namespace: marblerun
        path: "/mutate"
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        marblerun/monitor: marblerun
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None