apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: marble-injector
  labels:
    app: marble-injector
webhooks:
  - name: marble-injector.cluster.local
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1ERXhPREUwTWpFeU9Gb1hEVE14TURFeE56RTBNakV5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTklyCk5keHVjblJEZTZSTUhHSnVJaytWeC83Qmhzd3Y0d3hxY2tLZUpDWTBsZEdNTWlrcUZiaGFjUEtqd0JEVjVTTFgKRm9jUk1LdmMwYzJTL3FESWRHMHFEazI0UnVDSEFvWGU3ZllQTy9ETVlDMHB6cU5uZ3VtRHZ2OWUwMzE5UmlFUwpadksydlg4aGNFRGdTeDBMUnVyM01jSmkrZkVFRTc0ZXROUlh1YS84RDRBS2JHbDVDWEpxbDlrdmVUVFZYNC8vCi9icm9wR2xMRmczZ2s5OEdtM3dUbTBSa3FFMGRXa0ovbjg2dEtCbTFYZ1plcFFyNnFEalY5NnZZS0d3WTdydXYKOHk1Wk42RElaQUxpa0VKYXZRWUpoM3BubGVmVG5sa1RTbm80SHlzK08vUTNITklkWGYwYmR0a3FKVWFCcERMSwoveHRJK21TUEFPa0kyeUw0MmcwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSWVU5RUl2K3VRK0w5MzFNZXdXN2paL09zd3VUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFBZzF2Mkp6TQp0OVBJVEZUL3FJemFtUFpZOFVMaVhiclJvdGc2R0k0bXZHU0NiQUZuZDl3L25heHoxVFFhdWN5RDEvWS8xMDdKClZiWjlDZlJ5Q2plMldGdnNzTkZmN3JycXlCSmRYMEROc2RlKzFYeWM1aHROT3lwSC81MlgrZGlweWJvbkh3bzgKK1Q1V1NjTFRjWG9PelVqc0JXSWhwMjVmL2dOTlFISkx2U3NGWnZPMktoV3BLL3U4VDFEaVJFRWVJd2FJUGZoeQphWnlscjVpdHlnMlV4c2IzOTdkV2xOUE8rVnF1ZmhKdVhlQ3JLMS9JZE5ubGVoRFBIZDJNM1lJcWtISjM5LzJwCkljbElRWUVEd1pkWVYvU2ZQZEFpQmVXZ0w1QjdBcW8rNVhuU0d5cEhLcUFFVUp5dnJFV3gzQlYxeDB6Z0NZNXkKMzFrWXE0d2p3YlNyZ3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: marble-injector
        namespace: marblerun
        path: "/mutate"
    rules:
    - operations: ["CREATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        marblerun/monitor: marblerun
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None