apiVersion: v1
kind: Service
metadata:
  name: marble-injector-svc
  namespace: marblerun
  labels:
    app: marble-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector: 
    app: marble-injector